- name: play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: access url in task1
      ansible.builtin.debug:
        msg: URL in task1 = {{URL}}

    - name: access url in task2
      ansible.builtin.debug:
        msg: URL in task2 = {{URL}}

- name: var from a file
  hosts: all
  vars_files:
    - var-from-file.yml
  tasks:
    - name: access url in task1
      ansible.builtin.debug:
          msg: URL in task1 = {{URL}}

- name: var from a file
  hosts: all
  tasks:
    - name: access url in task1
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
          URL: tasks.google.com